version: 1
cron:
  - name: "PullingEventsByTypeSuccessful"
    url: "task/pulling_events_by_type_successful"
    schedule: "* * * * *"
  - name: "PullingGasFeeJob.perform"
    url: "task/get_gas_fee"
    schedule: "* * * * *"
#  - name: "DeleteListingsWhichExpirationJob.perform"
#    url: "task/delete_listings_which_expiration"
#    schedule: "10 * * * *"
  - name: "CheckUpdatingUsersJob.perform"
    url: "task/check_updating_users.json"
    schedule: "20 * * * *"
  - name: "PullingEventsByTypeTransfer"
    url: "task/pulling_events_by_type_transfer"
    schedule: "2 * * * *"
  - name: "HealthcheckWorkersJob.perform"
    url: "task/health_check_workers"
    schedule: "30 * * * *"
