version: 1
cron:
#  - name: "PullingEventCreatedForUpdateListingsJob"
#    url: "task/pulling_events_by_type_created"
#    schedule: "* * * * *"
#  - name: "DeleteListingsWhichExpirationJob.perform"
#    url: "task/delete_listings_which_expiration"
#    schedule: "10 * * * *"
  - name: "HealthcheckWorkersJob.perform"
    url: "task/health_check_workers"
    schedule: "30 * * * *"